version: "3.6"
services:
  backend:
    build: ./backend
    container_name: backend
    restart: unless-stopped
    ports:
      - 3001:3001
  frontend:
    build: ./frontend
    container_name: frontend
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    ports:
      - 3000:80
